### ISSUE TITLE
Uncaught exception at ChangeStreamCursor (watcher node)

### ISSUE THREAD

**Issue by Michwo** [steineey/node-red-contrib-mongodb4#28]
The following error happens on each deploy and restarts the whole node-red instance.

Microsoft Windows [Version 10.0.17763.5206]
Node-Red v.3.1.3

```
2024-01-10 11:13:18.332: 10 Jan 12:13:18 - [trace] runtime event: {"id":"runtime-state","payload":{"state":"start","deploy":true},"retain":true}
2024-01-10 11:13:18.332: 10 Jan 12:13:18 - [info] Started flows
2024-01-10 11:13:18.332: 10 Jan 12:13:18 - [trace] runtime event: {"id":"runtime-deploy","payload":{"revision":"ccb9291c11084ea0f40737873e4d15c1"},"retain":true}
2024-01-10 11:13:18.348: 10 Jan 12:13:18 - [debug] [inject:every 5 min] repeat = 300000
2024-01-10 11:13:18.348: 10 Jan 12:13:18 - [trace] git["rev-list","HEAD","--count"]
2024-01-10 11:13:18.348: 10 Jan 12:13:18 - [trace] git["log","--format=sha: %H%nparents: %p%nrefs: %D%nauthor: %an%ndate: %ct%nsubject: %s%n-----","-n 20"]
2024-01-10 11:13:18.348: 10 Jan 12:13:18 - [red] Uncaught Exception:
2024-01-10 11:13:18.348: 10 Jan 12:13:18 - [error] MongoNotConnectedError: Client must be connected before running operations
2024-01-10 11:13:18.348:     at executeOperationAsync (c:\node-red-be5\node_modules\mongodb\lib\operations\execute_operation.js:23:19)
2024-01-10 11:13:18.348:     at c:\node-red-be5\node_modules\mongodb\lib\operations\execute_operation.js:12:45
2024-01-10 11:13:18.348:     at maybeCallback (c:\node-red-be5\node_modules\mongodb\lib\utils.js:293:21)
2024-01-10 11:13:18.348:     at executeOperation (c:\node-red-be5\node_modules\mongodb\lib\operations\execute_operation.js:12:38)
2024-01-10 11:13:18.348:     at ChangeStreamCursor._getMore (c:\node-red-be5\node_modules\mongodb\lib\cursor\abstract_cursor.js:440:50)
2024-01-10 11:13:18.348:     at ChangeStreamCursor._getMore (c:\node-red-be5\node_modules\mongodb\lib\cursor\change_stream_cursor.js:102:15)
2024-01-10 11:13:18.348:     at node:internal/util:442:7
2024-01-10 11:13:18.348:     at new Promise (<anonymous>)
2024-01-10 11:13:18.348:     at bound _getMore (node:internal/util:428:12)
2024-01-10 11:13:18.348:     at next (c:\node-red-be5\node_modules\mongodb\lib\cursor\abstract_cursor.js:536:87)
```

**Comment by steineey** [comment]
Hi Michwo,
I fixed your issue. Please try out node-red-contrib-mongodb4@2.5.2
